title: Joseph J. Burton # your name (or website title) here
logo: "/images/Joe.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  Machine Learning Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/joe-burton-923871106/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

